### ISSUE TITLE
Crashes on spaces in filenames

### ISSUE THREAD

**Issue by gwern** [ShoufaChen/clone-anonymous4open#4]
Continuing https://anonymous.4open.science/repository/5c1049ba-109f-4a12-9d74-9a4a5130ce97/IN256_imgs.npz it seems the code crashes on any URL with spaces in it:

```
Clone...   /home/gwern/tmp/imgs/D Singular Values.png
Traceback (most recent call last):
  File "clone.py", line 101, in <module>
    clone_file(url, args.clone_dir)
  File "clone.py", line 58, in clone_file
    blob_soup = pull_html(root_url+href)
  File "clone.py", line 23, in pull_html
    response = urllib2.urlopen(req).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1292, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.6/http/client.py", line 1135, in putrequest
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
```

I guess the filenames are not being correctly escaped or URL-encoded? I'm not sure if it's right but I tried adding an encoding call:

```
diff --git a/clone.py b/clone.py
index 942bf64..31fd689 100644
--- a/clone.py
+++ b/clone.py
@@ -55,10 +55,14 @@ def clone_file(url, download, root_url='https://anonymous.4open.science'):
         if split_href[-1].split('.')[-1] == 'md' or split_href[-1] =='LICENSE':
             continue
 
-        blob_soup = pull_html(root_url+href)
+        blob_soup = pull_html(root_url+(urllib2.pathname2url(href)))
```

(I'm not sure this is right because it seems like the images may also exceed the Anonymous4open size limit and crash as in the other issue.)

Aside from the NPZ/JPG/PNG errors, this *seems* to finally download the repo correctly.

**Comment by ShoufaChen** [comment]
Thank your for your solution.

Fixed this follow your suggestion at https://github.com/ShoufaChen/clone-anonymous4open/commit/2c4c8559d1b85bc9222aad3b03bdc9e93d98643e
